name: Build
on: push
jobs:
  build:
    env:
      HOST: ${{ secrets.HOST }}
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4.1.7
        - name: Install Nodejs
          uses: actions/setup-node@v4.0.2
        - name: Install yarn
          run: npm install -g yarn
        - name: Build
          run: yarn && yarn build
        - name: Generate SSH Key File
          run: |
            mkdir .ssh
            chmod 700 .ssh
            ls -al
            echo "${{ secrets.RSA }}" > .ssh/id_rsa
            echo "View Contents:"
            cat .ssh/id_rsa
        - name: Upload Files
          run: |
            scp -i .ssh/id_rsa -r dist/* liubin@$HOST:/home/web/www
