name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4.1.7
        - name: Install Nodejs
          uses: actions/setup-node@v4.0.2
        - name: Install yarn
          run: npm install -g yarn
        - name: Build
          run: yarn --version && yarn build
        - name: Echo
          run: echo "Build completed.."